apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: board-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: wealist
  source:
    repoURL:  https://github.com/OrangesCloud/wealist-project-advanced-k8s.git
    targetRevision: k8s-deploy-dev
    path: k8s/helm/charts/board-service
    helm:
      valueFiles:
        - values.yaml
        - ../../environments/base.yaml
        - ../../environments/dev.yaml
      parameters:
        - name: global.imageRegistry
          value: ""  # ← CI가 ECR URL로 업데이트
        - name: image.repository
          value: "board-service"
        - name: image.tag
          value: "dev-latest"  # ← CI가 여기 업데이트
  destination:
    server: https://kubernetes.default.svc
    namespace: wealist-dev 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
